### ISSUE TITLE
Store session cookie in database

### ISSUE THREAD

**Issue by quom** [aogier/starlette-authlib#157]
Is there any way to store the cookie in a database after creating it?

My requirement is that I need to be able to logout all of a user's sessions without having to wait until the token expires. To do this I want to store the token in a database associated with the user such that on logout all of their sessions can be logged out by removing the cookies from the db.

Looking through the code it looks like this may only be possible by adding some custom middleware after the cookie encoding and saving it from there but this does not feel like a clean solution.

**Comment by aogier** [comment]
ciao, the point of this little addon is not having a database so let's try to find another solution :)

Beside a normal webapp flow where it's enough to `request.session.clear()` when you logout users, if you somehow want to logout a session you should then identify it via something whose lifecycle you control beside the browser requests. 

So yeah, I'd put a random string in session's data and in a db at login, then check for its presence at each subsequent request, invalidating session if that string is no longer on db.   
You could definitely pack this logic in a middleware which get configured after starlette_authlib and IMO that would the best option

**Comment by quom** [comment]
> So yeah, I'd put a random string in session's data and in a db at login, then check for its presence at each subsequent request, invalidating session if that string is no longer on db.

I think this would be the best solution. I was originally intending on just using JWTs with no database element but it doesn't fulfil a security requirement of being able to log a user's sessions out on request.

Thank you!

**Comment by aogier** [comment]
you welcome, have a nice day :)
