### ISSUE TITLE
Support for path attribute

### ISSUE THREAD

**Issue by gygabyte017** [aogier/starlette-authlib#239]
Hi, I see in the code that the path is statically set to "/", may it be set in the object initialization as starlette's SessionManager does?

**Comment by gygabyte017** [comment]
Created PR https://github.com/aogier/starlette-authlib/pull/240

**Comment by aogier** [comment]
Solved in 0.2.0 which is about to be published! Thanks for everything

**Comment by aogier** [comment]
erm 0.2.1 or >= 0.2 ... ciao!

**Comment by gygabyte017** [comment]
Thank you! I was going to work on this today but you've already done everything, thanks a lot 💯

**Comment by aogier** [comment]
thanks to you, your help was invaluable in realizing that I was not good at monitoring the evolutions of the middleware for which I developed a drop-in replacement. If you happen to use the new feature I would be happy to hear how it goes :)

ciao!

**Comment by gygabyte017** [comment]
I integrated that in my project, I confirm everything works as expected!
